spring:
  cloud:
    stream:
      bindings:
        input:
          destination: userTopic
          content-type: 'application/x-java-object;type=com.nbenja.springcloud.contract.springcloudcontractmessageexample.User'
          consumer:
            header-mode: raw
        output:
          content-type: application/json

