spring:
  cloud:
    stream:
      bindings:
        input:
          destination: userTopic
          content-type: application/json
          consumer.headerMode: raw

      default.consumer.headerMode: raw
