version: "2"
services:
  consul:
    image:  gliderlabs/consul-server:latest
    command: "-server -dev -bootstrap -ui"
    container_name: consul
    ports:
      - "8300:8300" # Used by servers to handle incoming requests from other agents
      - "8400:8400" # Used by all agents to handle RPC from the CLI
      - "8500:8500" # Used by clients to talk to the HTTP API (UI)